package_path: /home/tom/git_workspace/GrapheNetDefectDetector/yolo
exported_data_path: ${package_path}/data/original_data
dataset_path: ${package_path}/data/augmented_dataset
ssim_threshold: 0.8
split: 0.9
augmentation: [color, negative]
admitted_labels: ["0"]
